### ISSUE TITLE
无法查看历史会话

### ISSUE THREAD

**Issue by Dantetang** [xcy960815/vscode-chatgpt-plugin#3]
### Describe the Bug

使用中转api无法查看历史会话，点击无用

### Please tell us if you have customized any of the extension settings or whether you are using the defaults.

无法点击控件查看历史会话

**Comment by xcy960815** [comment]
啥意思？能给个截图不？

**Comment by Dantetang** [comment]
就是现在的新建会话是默认清空之前的会话，我以为是新建一个会话窗口，之前的会话历史仍然保留。

**Comment by Dantetang** [comment]
并且如果在vscode reload之前的窗口，会话记录也没了

**Comment by xcy960815** [comment]
每个vscode编译器会创建一个属于自己的会话存储实例，每个实例之间数据不共享，每个会话实例的生命周期跟vscode编译器一致，这样做是为了避免每次用户咨询问题携带过长的上下文，浪费用户的token

**Comment by Dantetang** [comment]
好吧，我明白了，谢谢你
