### ISSUE TITLE
希望添加自定义模型名称的功能

### ISSUE THREAD

**Issue by Theigrams** [xcy960815/vscode-chatgpt-plugin#4]
### Describe the feature

<img width="439" alt="image" src="https://github.com/xcy960815/vscode-chatgpt-plugin/assets/26341831/091e5bb1-6495-4e0b-89e4-7cd5f6a243d0">

如题，现在 GPT4-o 已经出来了，但插件还没更新，希望添加一个使用自定义模型名称的功能

**Comment by xcy960815** [comment]
好的，明天追加一下模型类型，并计划支持开放用户自填模型类型，感谢使用

**Comment by xcy960815** [comment]
插件新功能已经发布，0.1.4 版本已经支持自定义模型，21号没有发布是因为一直在纠结 想让model既支持下拉又支持输入，查阅了一些文档无果，所以在下面添加了一个 Custom Model 的参数，默认值为空，Custom Model 的优先级大于 Model的，如要使用列表提供的模型请将 Custom Model 置为空，祝你用的愉快

**Comment by Theigrams** [comment]
> 插件新功能已经发布，0.1.4 版本已经支持自定义模型，21号没有发布是因为一直在纠结 想让model既支持下拉又支持输入，查阅了一些文档无果，所以在下面添加了一个 Custom Model 的参数，默认值为空，Custom Model 的优先级大于 Model的，如要使用列表提供的模型请将 Custom Model 置为空，祝你用的愉快

非常感谢^_^
